Repository Team-4IGHTING/4Gamer-Client, pull requests merged in 2024-08, with the labels that each got.

#7 Feature/implement login member
  package-lock.json
  package.json
  src/App.tsx
  src/Router.tsx
  src/api/auth.ts
  src/api/client.ts
  src/api/member.ts
  src/api/types.ts
  src/components/BlackListContainer.tsx
  src/components/LoginContainer.tsx
  src/components/MemberContainer.tsx
  src/components/MessageContainer.tsx
  src/components/PostContainer.tsx
  src/components/css/GoogleButton.tsx
  src/components/css/Member.module.css
  src/components/css/UserButton.tsx
  src/components/css/index.css
  src/components/layout/Header.tsx
  src/constants.ts
  src/pages/BlackList.page.tsx
  src/pages/Login.page.tsx
  src/pages/Member.page.tsx
  src/pages/Message.page.tsx
  src/pages/Post.page.tsx
  src/pages/layout/LoginLayout.tsx
  src/pages/layout/RootLayout.tsx
  vite.config.js
  vite.config.mjs
Labels: feat

#8 Feature/#2 implement channel crud
  package-lock.json
  package.json
  src/App.tsx
  src/Router.tsx
  src/api/boardApi.ts
  src/api/captchaApi.ts
  src/api/channelApi.ts
  src/components/channels/ChannelContaner.tsx
  src/components/channels/channelitem.tsx
  src/main.tsx
  src/pages/channels/ ModifyChannel.tsx
  src/pages/channels/ChannelAdminPage.tsx
  src/pages/channels/ChannelDetailPage.tsx
  src/pages/channels/ChannelsPage.tsx
  src/pages/channels/CreateBoard.tsx
  src/pages/channels/CreateChannel.tsx
  src/pages/channels/ModifyBoard.tsx
  src/pages/channels/TableSort.module.css
  src/pages/layout/RootLayout.tsx
  yarn.lock
Labels: feat

#13 Bugfix/#12 fix game reveiw crud
  src/api/FourGamerClient.ts
  src/api/IgdbApi.ts
  src/api/VoteApi.ts
  src/api/gameReviewApi.ts
  src/components/game-review/GameReviewInput.tsx
  src/components/game-review/GameReviewItem.tsx
  src/pages/game-review/GameReviewList.page.css
  src/pages/game-review/GameReviewList.page.tsx
Labels: bug

#14 Feature/#9 implement google login
  package-lock.json
  package.json
  src/Router.tsx
  src/api/auth.ts
  src/api/client.ts
  src/components/LoginContainer.tsx
  src/components/channels/channelitem.tsx
  src/pages/GoogleLogin.page.tsx
  yarn.lock
Labels: feat

#16 Bugfix/#15 fix notification
  src/Router.tsx
  src/api/VoteApi.ts
  src/components/Common/PageFrame/PageFrame.tsx
  src/components/layout/Header.tsx
  src/components/layout/WebsocketConnection.tsx
  src/pages/game-review/GameReviewList.page.tsx
  src/pages/layout/RootLayout.tsx
Labels: bug

#19 Feature/implment admin blacklist
  .gitignore
  package-lock.json
  package.json
  src/Router.tsx
  src/api/channelApi.ts
  src/api/member.ts
  src/components/BlackListContainer.tsx
  src/components/MemberContainer.tsx
  src/components/UserProfile.tsx
  src/components/css/UserProfile.module.css
  yarn.lock
Labels: feat

#26 Feature/fix member and message
  src/Router.tsx
  src/api/member.ts
  src/components/MemberContainer.tsx
  src/components/MessageContainer.tsx
  src/components/UserProfile.tsx
  src/components/css/UserProfile.module.css
  src/components/css/message.css
Labels: bug, enhancement, feat

#25 Feat: 인기게시물 페이지 추가
  src/api/channelApi.ts
  src/components/channels/topPost.tsx
  src/pages/channels/ChannelAdminPage.tsx
Labels: feat

#22 Feature/#20 board update channel delete
  index.html
  src/Router.tsx
  src/api/boardApi.ts
  src/api/channelApi.ts
  src/api/member.ts
  src/components/BlackListContainer.tsx
  src/components/LoginContainer.tsx
  src/favicon.svg
  src/pages/channels/ModifyBoard.tsx
  src/pages/channels/ModifyChannel.tsx
Labels: feat

#29 Feature/implement igdb game top10
  src/Router.tsx
  src/api/IgdbApi.ts
  src/components/MemberContainer.tsx
  src/components/MessageContainer.tsx
  src/components/TopGameContainer.tsx
  src/pages/TopGame.page.tsx
Labels: feat

#30 Feature/#17 implement chat
  src/api/chat.ts
  src/api/gameReviewApi.ts
  src/assets/half-star.svg
  src/assets/index.ts
  src/assets/star-fill.svg
  src/assets/thumbs-down-blank.svg
  src/assets/thumbs-down-fill.svg
  src/assets/thumbs-up-blank.svg
  src/assets/thumbs-up-fill.svg
  src/components/Common/PageFrame/PageFrame.tsx
  src/components/UserProfile.tsx
  src/components/chat/Chat.css
  src/components/chat/Chat.tsx
  src/components/game-review/GameReviewInput.css
  src/components/game-review/GameReviewInput.tsx
  src/components/game-review/GameReviewItem.css
  src/components/game-review/GameReviewItem.tsx
  src/components/game-review/GameReviewScore.tsx
  src/components/layout/WebsocketConnection.tsx
Labels: bug, feat

#32 Feature/#17 implement chat
  src/components/MemberContainer.tsx
  src/components/chat/Chat.tsx
  src/components/layout/WebsocketConnection.tsx
  src/pages/game-review/GameReviewList.page.css
  src/pages/game-review/GameReviewList.page.tsx
Labels: bug, feat

#34 Feature/#4 implement board and post pages
  package-lock.json
  package.json
  src/App.tsx
  src/Router.tsx
  src/api/boardApi.ts
  src/api/channelApi.ts
  src/api/client.ts
  src/api/comment.ts
  src/api/fileUpload.ts
  src/api/posts.ts
  src/api/reaction.ts
  src/components/BlackListContainer.tsx
  src/components/Common/PageFrame/PageFrame.tsx
  src/components/Post/PostDetail/Comment.tsx
  src/components/Post/PostDetail/PostDetail.tsx
  src/components/Post/PostList/PostSummary.tsx
  src/components/TextEditor/TextEditor.css
  src/components/TextEditor/TextEditor.tsx
  src/components/UserProfile.tsx
  src/components/channels/TopPostList.tsx
  src/components/channels/topPost.tsx
  src/constants.ts
  src/pages/Home.page.tsx
  src/pages/channels/ChannelAdminPage.tsx
  src/pages/channels/ChannelDetailPage.tsx
  src/pages/post/NewPost.page.tsx
  src/pages/post/PostDetail.page.tsx
  src/pages/post/PostEdit.page.tsx
  src/pages/post/PostList.page.tsx
  src/responseTypes.ts
  src/util/dateUtil.ts
  src/util/numberUtil.ts
  tsconfig.json
  vite.config.js
  yarn.lock
Labels: feat

#35 Feature/#33 cicd
  .github/workflows/deploy.yml
  .github/workflows/viteCI.yml
  build.sh
  index.html
  src/4gamerLogo.png
  src/api/captchaApi.ts
  src/components/Common/PageFrame/PageFrame.tsx
  src/components/LoginContainer.tsx
  vercel.json
Labels: feat

#37 Bugfix/channels admin
  src/components/Common/PageFrame/PageFrame.tsx
  src/components/channels/ChannelContaner.tsx
  src/components/channels/channelitem.tsx
Labels: bug

#38 Feat: 채널 상세 페이지
  src/components/channels/topPost.tsx
  src/pages/channels/ChannelDetailPage.tsx
  src/pages/post/PostList.page.tsx
Labels: feat

#40 Feature/#39 fix multiple bugs on various regions
  src/Router.tsx
  src/api/channelApi.ts
  src/api/posts.ts
  src/components/LoginContainer.tsx
  src/components/MessageContainer.tsx
  src/components/Post/PostDetail/PostDetail.tsx
  src/components/channels/ChannelContaner.tsx
  src/components/channels/channelitem.tsx
  src/components/channels/topPost.tsx
  src/components/game-review/GameReviewInput.tsx
  src/pages/BlackList.page.tsx
  src/pages/Login.page.tsx
  src/pages/Member.page.tsx
  src/pages/Message.page.tsx
  src/pages/Post.page.tsx
  src/pages/TopGame.page.tsx
  src/pages/channels/ChannelAdminPage.tsx
  src/pages/channels/ChannelDetailPage.tsx
  src/pages/channels/ChannelsPage.tsx
  src/pages/channels/CreateBoard.tsx
  src/pages/channels/CreateChannel.tsx
  src/pages/channels/ModifyBoard.tsx
  src/pages/channels/ModifyChannel.tsx
  src/pages/game-review/GameReviewList.page.tsx
  src/pages/post/NewPost.page.tsx
  src/pages/post/PostDetail.page.tsx
  src/pages/post/PostEdit.page.tsx
  src/pages/post/PostList.page.tsx
Labels: bug, feat

#42 Fix: 변경된 쪽지 페이지 경로 반영
  src/components/layout/WebsocketConnection.tsx
Labels: bug

#43 🚑️ Fix: update member-related page regarding router
  src/pages/Member.page.tsx
  src/pages/Message.page.tsx
  src/pages/Post.page.tsx
Labels: bug

#46 Bugfix/chat availability notification
  src/components/UserProfile.tsx
  src/components/chat/Chat.css
  src/components/chat/Chat.tsx
  src/components/layout/WebsocketConnection.tsx
Labels: bug

#44 🚑️ Fix: 게시물 목록 페이지에서 반응이 즉각적으로 피드백되지 않는 오류 수정
  src/components/Post/PostList/PostSummary.tsx
Labels: bug

#48 Bugfix/post upload and blacklist
  src/components/game-review/GameReviewInput.tsx
  src/pages/post/NewPost.page.tsx
  src/pages/post/PostEdit.page.tsx
Labels: bug

#47 Fix: 채널 및 멤버 실패 정보 띄움
  src/components/MemberContainer.tsx
  src/pages/channels/ChannelDetailPage.tsx
  src/pages/channels/CreateBoard.tsx
  src/pages/channels/CreateChannel.tsx
  src/pages/channels/ModifyBoard.tsx
  src/pages/channels/ModifyChannel.tsx
Labels: bug

#50 Bugfix/#49 gameReview vote
  src/components/MemberContainer.tsx
  src/components/game-review/GameReviewItem.tsx
Labels: bug

#51 Fix: 리액션 수정
  src/components/MemberContainer.tsx
  src/components/Post/PostDetail/PostDetail.tsx
  src/pages/post/PostList.page.tsx
Labels: bug

#53 Fix: 내 리뷰 외 다른 리뷰의 별점이 왼쪽으로 정렬되는 부분 수정
  src/components/game-review/GameReviewItem.tsx
Labels: bug
